<a href="https://colab.research.google.com/github/chebbin/datasci_5_statistics/blob/main/code/507_t_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from scipy.stats import ttest_ind
from numpy.matrixlib import defmatrix

In [ ]:
df = pd.read_csv('/content/diabetes_binary_health_indicators_BRFSS2015.csv')
df

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,5.0,0.0,1.0,5.0,6.0,7.0
253676,1.0,1.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
253677,0.0,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0
253678,0.0,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,7.0,5.0,1.0
253679,1.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [ ]:
df.dtypes

Diabetes_binary         float64
HighBP                  float64
HighChol                float64
CholCheck               float64
BMI                     float64
Smoker                  float64
Stroke                  float64
HeartDiseaseorAttack    float64
PhysActivity            float64
Fruits                  float64
Veggies                 float64
HvyAlcoholConsump       float64
AnyHealthcare           float64
NoDocbcCost             float64
GenHlth                 float64
MentHlth                float64
PhysHlth                float64
DiffWalk                float64
Sex                     float64
Age                     float64
Education               float64
Income                  float64
dtype: object

In [ ]:
df.describe()

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
count,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,...,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000
mean,0.139333,0.429001,0.424121,0.962670,28.382364,0.443169,0.040571,0.094186,0.756544,0.634256,...,0.951053,0.084177,2.511392,3.184772,4.242081,0.168224,0.440342,8.032119,5.050434,6.053875
std,0.346294,0.494934,0.494210,0.189571,6.608694,0.496761,0.197294,0.292087,0.429169,0.481639,...,0.215759,0.277654,1.068477,7.412847,8.717951,0.374066,0.496429,3.054220,0.985774,2.071148
min,0.000000,0.000000,0.000000,0.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,1.000000,24.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,6.000000,4.000000,5.000000
50%,0.000000,0.000000,0.000000,1.000000,27.000000,0.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,8.000000,5.000000,7.000000
75%,0.000000,1.000000,1.000000,1.000000,31.000000,1.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,0.000000,3.000000,2.000000,3.000000,0.000000,1.000000,10.000000,6.000000,8.000000
max,1.000000,1.000000,1.000000,1.000000,98.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,5.000000,30.000000,30.000000,1.000000,1.000000,13.000000,6.000000,8.000000

# T-Test

## There is a relationship between BMI and smoking status
The BMI levels of people are different in smokers and non-smokers

Null Hypothesis: There is no relationship between BMI and smoking status

In [ ]:
# # Split the data into two groups: BMI_obese and BMI_nonobese
BMI_obese = df[df['BMI'] >= 30]['BMI']
BMI_obese

0         40.0
6         30.0
8         30.0
11        34.0
14        33.0
          ...
253660    34.0
253661    33.0
253672    30.0
253673    42.0
253675    45.0
Name: BMI, Length: 87851, dtype: float64

In [ ]:
BMI_obese.describe()

count    87851.000000
mean        35.127295
std          6.413377
min         30.000000
25%         31.000000
50%         33.000000
75%         37.000000
max         98.000000
Name: BMI, dtype: float64

In [ ]:
BMI_nonobese = df[df['BMI'] < 30]['BMI']
BMI_nonobese

1         25.0
2         28.0
3         27.0
4         24.0
5         25.0
          ...
253674    27.0
253676    18.0
253677    28.0
253678    23.0
253679    25.0
Name: BMI, Length: 165829, dtype: float64

In [ ]:
BMI_nonobese.describe()

count    165829.000000
mean         24.809111
std           2.855315
min          12.000000
25%          23.000000
50%          25.000000
75%          27.000000
max          29.000000
Name: BMI, dtype: float64

In [ ]:
# Separate the obese people in relation to smoking 100 cigarettes in a lifetime
BMI_obese_data = df[df['BMI'] >= 30]['Smoker']
BMI_obese_data

0         1.0
6         1.0
8         1.0
11        1.0
14        1.0
         ...
253660    1.0
253661    0.0
253672    1.0
253673    0.0
253675    0.0
Name: Smoker, Length: 87851, dtype: float64

In [ ]:
# Separate the non obese people in relation to smoking 100 cigarettes in a lifetime
BMI_nonobese_data = df[df['BMI'] < 30]['Smoker']
BMI_nonobese_data

1         1.0
2         0.0
3         0.0
4         0.0
5         1.0
         ...
253674    0.0
253676    0.0
253677    0.0
253678    0.0
253679    0.0
Name: Smoker, Length: 165829, dtype: float64

## The T-value of 9 indicates that there is a large difference between the two data sets in regards to smoking.

The small P value indicates that the null hypothesis should be rejected.

In [ ]:
t_stat, p_val = ttest_ind(BMI_obese_data, BMI_nonobese_data, equal_var=False)  # Assuming unequal variances with Welch's t-test # noqa

print(f"T-statistic: {t_stat}")
print(f"P-value: {p_val}")

T-statistic: 9.172926241905087
P-value: 4.650489186690934e-20